version: "3.9"
services:
  bot:
    build: .
    restart: always
    environment:
      - CHANNEL_ID
      - DISCORD_TOKEN
      - MONGODB_CONNECTION_STRING
      - PREFIX
  mongo:
    image: mongo:5.0.3
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - mz-covid-bot-db:/data/db
volumes:
  mz-covid-bot-db:
    external: true